### ISSUE TITLE
Why does this lib need pytest 4.6 in published package?

### ISSUE THREAD

**Issue by ig0rsky** [dydxprotocol/dydx-v3-python#151]
We're installing this lib using pip as it doesn't exist on conda-forge. Pip uninstalls our pytest package v7.3 and then installs pytest 4.6 which is quite old and doesn't work in our environment. I'm wondering why it's necessary to have pytest in requirements.txt and not requirements.develop.txt or something along those lines? 

``` txt
Installing collected packages: pytest
  Attempting uninstall: pytest
    Found existing installation: pytest 7.1.0
    Uninstalling pytest-7.1.0:
      Successfully uninstalled pytest-7.1.0
Successfully installed pytest-4.6.11
```

**Comment by BrendanChou** [comment]
Thanks for the question, fixed now
