### ISSUE TITLE
Relax dependencies requirements to be compatible with other libraries, like Solana

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [dydxprotocol/dydx-v3-python#152]
I'm working on a project which is using `dydx-python` and `dydx-v3-python` libraries.

Unfortunately, for both of them, they require the exact version of `2.22.0` of the `requests` library.
Because of that, I'm having a dependency conflict with the [Solana library ](https://pypi.org/project/solana/#history) which from the very beginning requires requests>=2.24.

So, how about we update the requirements.txt of these libraries (`dydx-v3-python` and `dydx-python`) to work with other versions of the requests as well? And maybe relax the other dependencies a little bit too?

**Comment by eduardo-ridian** [comment]
Any updates on this? Im also having issues with Streamlit and Alpaca

**Comment by BrendanChou** [comment]
Fixed, now allows `requests>=2.22.0,<3.0.0`
