### ISSUE TITLE
Cytoolz 0.11.2 doesn't build

### ISSUE THREAD

**Issue by healthyred** [dydxprotocol/dydx-v3-python#168]
Can you guys update the requirements to use a different cytoolz version?

https://github.com/pytoolz/cytoolz/issues/157

I believe 0.11.2 has some issues building / installing on some machines.

**Comment by healthyred** [comment]
Can you guys update the requirements to use a different cytoolz version? 

https://github.com/pytoolz/cytoolz/issues/157

I believe 0.11.2 has some issues building / installing on some machines.

**Comment by julian-dotcom** [comment]
I have the same problem

**Comment by kylesvec** [comment]
same issue here

**Comment by vincent7q** [comment]
if you are using visualstudio, you have to install visual studio build tools and include the following components
1. MSVC v1xx
2. Windows 11/10 SDK
3. C++ CMake tools for windows
4. testing tools core features
5. C== AddressSanitizer

**Comment by doobran** [comment]
Can you please just change cytoolz==0.12.0 in requirements, that works fine.

**Comment by doobran** [comment]
You can point to a different requirements text file with cytoolz==0.12.0 if you want and it will install:

pip install dydx-v3-python -r requirements.txt --no-dependencies

Little bit dodgy because some functions might not work but its a interim solution.

**Comment by menaitm** [comment]
Please can we update to `cytoolz==0.12.0`

**Comment by SC4RECOIN** [comment]
using python 3.8 instead of 3.11 worked for me

**Comment by BrendanChou** [comment]
Fixed: https://github.com/dydxprotocol/dydx-v3-python/pull/191
