### ISSUE TITLE
python package dependencies conflict: ccxt vs dydx - setuptools version

### ISSUE THREAD

**Issue by normanlmfung** [dydxprotocol/dydx-v3-python#178]
hi Dydx team, any chance you can upgrade setuptools version?

ccxt 2.0.1 depends on setuptools>=60.9.0
dydx-v3-python 1.9.1 depends on setuptools==50.3.2

atm the work around is take dydx out of requirements.txt:
pip install -r requirements.txt

Then separate install dydx:
   pip install dydx-v3-python==1.9.1 --user

Thanks

**Comment by BrendanChou** [comment]
`setuptools>=60.0.0` now in this package
