### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by victorsemeraro** [dydxprotocol/dydx-v3-python#52]
Hello, 

I am new to the dydx API. I am having trouble connecting. As a test, I am just pulling public market data but I get this error:

"ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v3/markets (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020763C0BD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"

The code is below

`
import dydx3 as dydx

public_client = dydx.Client(
    host='http://localhost:8080',
)
public_client.public.get_markets()
 `

**Comment by deependersingla** [comment]
Will not host should be Ether node. Are you running node locally at 8080?

**Comment by victorsemeraro** [comment]
How can I check if I am running the node locally at 8080. 

My process is simply typing 'geth' into the terminal and letting it run

**Comment by CongZhengithub** [comment]
hi, I am new to the dydx exchange. I also met this problem. Can you explain how to solve this problem? When I want to create stack key.

**Comment by dyustc** [comment]
I have the same problem when I try to run the onboard script
