### ISSUE TITLE
求助  下单签名错误问题 

### ISSUE THREAD

**Issue by JiaMingYu** [dydxprotocol/dydx-v3-python#61]
client = Client(
    network_id=NETWORK_ID_MAINNET,
    host=API_HOST_MAINNET,
    default_ethereum_address=ETH_ADDRESS,
    web3=Web3(Web3.HTTPProvider(WEB_PROVIDER_URL)),
    api_key_credentials=api_key,
    stark_private_key=STARK_KEY,
)
# 发送订单
account_response = client.private.get_account()
position_id = account_response['account']['positionId']
print(position_id)

order_params = {
    'position_id': position_id,
    'market': MARKET_ETH_USD,
    'side': ORDER_SIDE_BUY,
    'order_type': ORDER_TYPE_LIMIT,
    'post_only': False,
    'size': '0.01',
    'price': '2400',
    'limit_fee': '0.0018',
    "expiration_epoch_seconds": int(time.time()) + 4 * 7 * 1440 * 60,
}
order_response = client.private.create_order(**order_params)
order_id = order_response['order']['id']

返回

Traceback (most recent call last):
  File "api.py", line 54, in <module>
    order_response = client.private.create_order(**order_params)
  File "/Users/Desktop/dydx/dydx3/modules/private.py", line 463, in create_order
    order,
  File "/Users/Desktop/dydx/dydx3/modules/private.py", line 82, in _post
    data
  File "/Users/Desktop/dydx/dydx3/modules/private.py", line 69, in _private_request
    data,
  File "/Users/Desktop/dydx/dydx3/helpers/requests.py", line 27, in request
    raise DydxApiError(response)
dydx3.errors.DydxApiError: DydxApiError(status_code=400, response={'errors': [{'msg': 'Invalid signature for order'}]})

求助啊 查询订单 撤销订单 都没问题

**Comment by CongZhengithub** [comment]
Sorry, what's the WEB_PROVIDER_URL?

**Comment by JiaMingYu** [comment]
WEB_PROVIDER_URL = 'https://mainnet.infura.io/v3/58d02eb7bdd844f88f582fe843389325'

**Comment by CongZhengithub** [comment]
When I use the infura node, It reminds me 'The method eth_signTypedData does not exist/is not available'. Do you have some idea about this?

**Comment by JiaMingYu** [comment]
找到原因了，是因为我使用的STARK_KEY 是 浏览器中的，清除缓存之后会重新生成。因此签名始终不通过

**Comment by jueduizone** [comment]
@JiaMingYu Hi ,请教一下，正确的 STARK_KEY 应该从哪里来？

**Comment by JiaMingYu** [comment]
@jueduizone  浏览器打开dydx 并用钱包连接，单机右键->检查-> Application ->storage -> local -> https://trade.dydx.exchange -> STARK_KEY_PAIRS

**Comment by CongZhengithub** [comment]
如果使用examples里面的onboard.py可以生成stack key吗 @JiaMingYu

**Comment by woshiopqt** [comment]
你好，我用这个方法，但是还是一直报签名错误，和你之前报错一样的，我按照你的方法在浏览器里边找的starkprivatekey，并附给了client，但是还是依旧报错。

**Comment by dyustc** [comment]
> WEB_PROVIDER_URL = 'https://mainnet.infura.io/v3/58d02eb7bdd844f88f582fe843389325'

is this url specific for u, all anyone use mainnet should use this? @JiaMingYu thanks

**Comment by dyustc** [comment]
> 如果使用examples里面的onboard.py可以生成stack key吗 @JiaMingYu

@CongZhengithub 我碰到一样的问题了， 你解决这个了吗

**Comment by CrazyOptimist** [comment]
你好 @JiaMingYu !
你解决了这个问题吗？ 我遇到了同样的问题，如果你让我知道你是如何解决它的，我将不胜感激。

**Comment by JiaMingYu** [comment]
@CongZhengithub stack key 是需要在打开dydx 存储在浏览器中的 你需要找到它
@woshiopqt  我之前也出现过 已经在浏览器中找到了 但是还是有错误，是因为我手机钱包也打开dydx了 会又生成一份 stack key 
@dyustc   这个应该是固定的吧。。。  stack key 需要在web浏览器中找到它  怎么找在上面回答中， 因为这个事dydx生成的

**Comment by CrazyOptimist** [comment]
https://github.com/dydxprotocol/dydx-v3-python/issues/96#issuecomment-986915988
Hope this helps!

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @JiaMingYu)
