### ISSUE TITLE
'The method eth_signTypedData does not exist/is not available'

### ISSUE THREAD

**Issue by CongZhengithub** [dydxprotocol/dydx-v3-python#62]
Warning: Failed to derive default API key credentials: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'}
Traceback (most recent call last):
  File "/dydxDataWss.py", line 20, in <module>
    stark_private_key = client.onboarding.derive_stark_key()
  File "/usr/local/lib/python3.9/site-packages/dydx3/modules/onboarding.py", line 124, in derive_stark_key
    signature = self.signer.sign(
  File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/sign_off_chain_action.py", line 38, in sign
    typed_signature = self.signer.sign(
  File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/signers.py", line 51, in sign
    raw_signature = self.web3.eth.signTypedData(
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'}

When I try to create the stack key, I find this error. Does someone know how to solve it ?

**Comment by CongZhengithub** [comment]
when I run the examples/onboard.py file.

**Comment by CongZhengithub** [comment]
@Kenadia Can you provide a solution about this problem?

**Comment by bala782** [comment]
i met the same problem. when using Ganache node, everything is ok, but using the etherum mainnet, this problem happens, i don't know why。anyone can help?

**Comment by Bruhwuh123** [comment]
did you guys find a sollution? It seems to be infura not accepting signing, but what node does accept that? a Private one?

**Comment by fastener** [comment]
did you guys find a sollution? It seems to be infura not accepting signing, but what node does accept that? a Private one?

**Comment by liuqiba** [comment]
The same with you are

**Comment by liavkoren** [comment]
Someone opened an issue with web3.py about this, even though it is actually a dydx issue. One of the web3 maintainers has provided a pretty nice answer, it may shed some light: https://github.com/ethereum/web3.py/issues/2097

Maybe one of the DyDx maintainers can help with a web3 issue to return the favor ; )

**Comment by caiyundong** [comment]
For my practice, we have tried to use infura and quiknode, unluckily both don't implement the eth_signTyped Data, which is available for the MetaMask though. As it is just a wallet but not a node, I have no idea to set the web3's httpprovider. 

Our last straw is to use the STARK_KEY_PAIR, which contains the private key, public key as well as the y-coordinate from the metamask. It can be found at the "Right Click of dydx trading webpage after linking the metamask wallet -> Inspection->Application->Local Storage->http://trade.dydx....->" together with the api key credentials.

One thing to note is that for the Stark keys (private key, public key, public y coordinate), there is a need to modify a bit, e.g. "02312321" ->"0x2312321" in your code, otherwise you might meet the private key/public key mismatch problem.

**Comment by dyustc** [comment]
> i met the same problem. when using Ganache node, everything is ok, but using the etherum mainnet, this problem happens, i don't know why。anyone can help?

when using Ganache node, I came across even more bug... Is this relevant to locations?

it said 

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff071f6b1d0>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by caiyundong** [comment]
> > Warning: Failed to derive default API key credentials: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'} Traceback (most recent call last): File "/Users/zhengcong/Documents/hkust/financial math/gitlab_py/apps/DataPlatform/MarketDataService/DYDX/dydxDataWss.py", line 20, in stark_private_key = client.onboarding.derive_stark_key() File "/usr/local/lib/python3.9/site-packages/dydx3/modules/onboarding.py", line 124, in derive_stark_key signature = self.signer.sign( File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/sign_off_chain_action.py", line 38, in sign typed_signature = self.signer.sign( File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/signers.py", line 51, in sign raw_signature = self.web3.eth.signTypedData( File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller result = w3.manager.request_blocking(method_str, File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking return self.formatted_response(response, File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response raise ValueError(response["error"]) ValueError: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'}
> > When I try to create the stack key, I find this error. Does someone know how to solve it ?
> 
> Can I ask what WEB_PROVIDER_URL you are using for ETH mainnet on metamask?

There is no web_provider_url for the metamask as it is a wallet not a node. I fetch the keys from the browser. Cannot figure the way to get them from the API.
![sc](https://user-images.githubusercontent.com/1865812/136160015-b6e858bc-0845-4611-bf6e-eb35588a4982.jpg)

**Comment by CongZhengithub** [comment]
> > Warning: Failed to derive default API key credentials: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'} Traceback (most recent call last): File "/Users/zhengcong/Documents/hkust/financial math/gitlab_py/apps/DataPlatform/MarketDataService/DYDX/dydxDataWss.py", line 20, in stark_private_key = client.onboarding.derive_stark_key() File "/usr/local/lib/python3.9/site-packages/dydx3/modules/onboarding.py", line 124, in derive_stark_key signature = self.signer.sign( File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/sign_off_chain_action.py", line 38, in sign typed_signature = self.signer.sign( File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/signers.py", line 51, in sign raw_signature = self.web3.eth.signTypedData( File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller result = w3.manager.request_blocking(method_str, File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking return self.formatted_response(response, File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response raise ValueError(response["error"]) ValueError: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'}
> > When I try to create the stack key, I find this error. Does someone know how to solve it ?
> 
> Can I ask what WEB_PROVIDER_URL you are using for ETH mainnet on metamask?

**Comment by dyustc** [comment]
> > > Warning: Failed to derive default API key credentials: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'} Traceback (most recent call last): File "/Users/zhengcong/Documents/hkust/financial math/gitlab_py/apps/DataPlatform/MarketDataService/DYDX/dydxDataWss.py", line 20, in stark_private_key = client.onboarding.derive_stark_key() File "/usr/local/lib/python3.9/site-packages/dydx3/modules/onboarding.py", line 124, in derive_stark_key signature = self.signer.sign( File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/sign_off_chain_action.py", line 38, in sign typed_signature = self.signer.sign( File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/signers.py", line 51, in sign raw_signature = self.web3.eth.signTypedData( File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller result = w3.manager.request_blocking(method_str, File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking return self.formatted_response(response, File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response raise ValueError(response["error"]) ValueError: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'}
> > > When I try to create the stack key, I find this error. Does someone know how to solve it ?
> > 
> > 
> > Can I ask what WEB_PROVIDER_URL you are using for ETH mainnet on metamask?
> 
> There is no web_provider_url for the metamask as it is a wallet not a node. I fetch the keys from the browser. Cannot figure the way to get them from the API. ![sc](https://user-images.githubusercontent.com/1865812/136160015-b6e858bc-0845-4611-bf6e-eb35588a4982.jpg)

hi, I did the same, I fetched the keys from the browser, but just the stark key pair, we still need the API key to access private functions right? have you succeed? @caiyundong

**Comment by caiyundong** [comment]
You can see that there is a "API_KEY_PAIRS" there.

**Comment by dyustc** [comment]
@caiyundong  I wrote this according to the[ dydx documentation](https://docs.dydx.exchange/?json#creating-and-signing-requests), but it seems the stark key isn't used here, kind of strange. Anyway, it isn't working.

**Comment by CNich** [comment]
I fetched the keys from the browser as @caiyundong said above and added '0x' to stark keys, and the private endpoints are working except for create_order (haven't tried withdraw yet). I get the error `DydxApiError: DydxApiError(status_code=400, response={'errors': [{'msg': 'Invalid signature for order'}]})
`. Are my stark keys wrong? How does metamask do the signing?

**Comment by caiyundong** [comment]
1. For the stark_private_key, stark_public_key, stark_public_key_y_coordinate, you can use "stark_private_key = hex(int("0x"+stark_private_key, base=16))" to convert if it doesn't start with 0x, may not just add 0x at the front.
2. You may check if you have used correct position_id for place_order (position_id = dydx_driver.get_accounts()["accounts"][0]["positionId"])

**Comment by CNich** [comment]
Ah, my position_id was wrong, I set it to 1 since I saw that in the docs, didn't realize I needed to use my own. Thanks @caiyundong for the help!

**Comment by caiyundong** [comment]
@CNich exactly same as me, it shows that the documentation is not good enough.

**Comment by NumberUn** [comment]
Hi all. What if I have no keys in browser?
![image](https://user-images.githubusercontent.com/86023688/146198226-ed397f17-2de3-4e58-aa22-01d9ad11f74b.png)

**Comment by caiyundong** [comment]
Have you connected the wallet e.g. metamask?

**Comment by cfa532** [comment]
> One thing to note is that for the Stark keys (private key, public key, public y coordinate), there is a need to modify a bit, e.g. "02312321" ->"0x2312321" in your code, otherwise you might meet the private key/public key mismatch problem.

you saved my week!

**Comment by oussamabng** [comment]
@caiyundong i did everything like u said , but i still have `DydxApiError(status_code=400, response={'errors': [{'msg': 'Invalid signature for order'}]})` please help me.

stark_private_key = 'XXX'
STARK_PRIVATE_KEY = hex(int("0x"+stark_private_key, base=16))

account_response = private_client.private.get_account()
position_id = account_response.data['account']['positionId']
print(position_id)

**Comment by caiyundong** [comment]
You can create a read-only key and send to me (yundong.cai@gmail.com). I can give a try. I haven't worked on DYDX for quite a long time. @oussamabng
