### ISSUE TITLE
the method eth_signTypedData does not exist/is not available

### ISSUE THREAD

**Issue by vanshajchadha** [dydxprotocol/dydx-v3-python#74]
Running the python client gives the following error:

ValueError: {'code': -32601, 'message': 'the method eth_signTypedData does not exist/is not available'}

This is the code that was executed:

    # Ganache test address.
    ETHEREUM_ADDRESS = '0xa6DAD6c64F8795CDe5AfB2A031B880a6849edE73'

    # Ganache node.
    WEB_PROVIDER_URL = 'http://localhost:8545'

    API_HOST_ROPSTEN = 'https://api.stage.dydx.exchange'

    NETWORK_ID_ROPSTEN = 3

    client = Client(
        network_id=NETWORK_ID_ROPSTEN,
        host=API_HOST_ROPSTEN,
        default_ethereum_address=ETHEREUM_ADDRESS,
        web3=Web3(Web3.HTTPProvider(WEB_PROVIDER_URL)),
    )

**Comment by vanshajchadha** [comment]
Found that using Ganache solved the problem, however, using Geth, the error arises regardless of which network one connects to or the web 3 provider methods you employ.

**Comment by yanue** [comment]
same problem
